# Generated by Django 2.0 on 2018-12-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('role_id', models.IntegerField(verbose_name='角色ID')),
                ('username', models.CharField(max_length=128, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='最后一次登陆时间')),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
    ]
